### ISSUE TITLE
Returns `noop` on Windows 10

### ISSUE THREAD

**Issue by adi-works** [kapetan/electron-drag#7]
I went through the code since it's neat and simple. It returns as `noop`. It's really strange actually. I don't understand how Electron guys wanted us to make draggable custom title-bars while events cannot pass through. With code age I'm suspecting this approach needs an update.

**Comment by kapetan** [comment]
I tried testing it on Window 10 (64-bit) with newest electron prebuilt version (1.4.15) and it works as expected. Are you sure you are [compiling the module correctly](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md) as it says in the readme?

**Comment by adi-works** [comment]
Hi, yes I read about that, but misunderstood it somehow. I've now rebuilt electron using the 2nd method, but the issue persists. Another thing I'd like to point out. The fallback you introduce isn't part of the plugin, which I'm not sure why? but anyway, I added it manually and it's obviously triggered because `drag` returns with `noop`.

**Comment by kapetan** [comment]
I didn't include the fallback so that people wouldn't get surprised by the sudden change in behaviour. But I don't know why the module does not work for you. Can you post more information, e.g. electron version and any output in the terminal when building the module (maybe try manually building the module as it says on the linked page).

**Comment by adi-works** [comment]
Ok, I've added electron-rebuild to npm start to make it persistent and seems like it's sorted now.

**Comment by kapetan** [comment]
Glad to hear that.
